teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.8
      -
        axis: 3
        target: angular.z
        scale: 0.8

  head_down:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0, -0.1]
    buttons: [0] # A

  head_right:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [-0.1, 0]
    buttons: [1] # B

  head_left:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0.1, 0]
    buttons: [2] # X

  head_up:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0, 0.1]
    buttons: [3] # Y

  close_gripper:
    type: action
    action_name: /gripper_controller/increment
    action_goal:
      increment_by: [-0.01]
    buttons: [5] # RB

  open_gripper:
    type: action
    action_name: /gripper_controller/increment
    action_goal:
      increment_by: [0.01]
    buttons: [4] # LB

  torso_up:
    type: action
    action_name: /torso_controller/increment
    action_goal:
      increment_by: [0.05]
    buttons: [7] # +

  torso_down:
    type: action
    action_name: /torso_controller/increment
    action_goal:
      increment_by: [-0.05]
    buttons: [6] # -

  say_excuse:
    type: action
    action_name: /tts
    action_goal:
      speakerName: "asd"
      rawtext:
        text: "excuse me"
        lang_id: "en_US"
    buttons: [9] # R3

  say_thanks:
    type: action
    action_name: /tts
    action_goal:
      speakerName: "asd"
      rawtext:
        text: "thanks"
        lang_id: "en_US"
    buttons: [10, 0] # L3 + 

